version: '3.6'
services:
  minio1:
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    volumes:
     - mndata1:/home/sdci/docker/minio/data
    ports:
     - "9001:9000"
    environment:
     MINIO_ACCESS_KEY: minio
     MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
  minio2:
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    volumes:
     - mndata2:/home/sdci/docker/minio/data
    ports:
     - "9002:9000"
    environment:
     MINIO_ACCESS_KEY: minio
     MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
  minio3:
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    volumes:
     - mndata3:/home/sdci/docker/minio/data
    ports:
     - "9003:9000"
    environment:
     MINIO_ACCESS_KEY: minio
     MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
  minio4:
    image: minio/minio:RELEASE.2018-12-27T18-33-08Z
    volumes:
     - mndata4:/home/sdci/docker/minio/data
    ports:
     - "9004:9000"
    environment:
     MINIO_ACCESS_KEY: minio
     MINIO_SECRET_KEY: minio123
    command: server http://minio1/data http://minio2/data http://minio3/data http://minio4/data 
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    container_name: elasticsearch
    environment:
      - node.name=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    privileged: true
    volumes:
      - esdata1:/home/sdci/docker/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    links: 
      - minio1  
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    container_name: elasticsearch2
    environment:
      - node.name=es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    privileged: true
    volumes:
      - esdata2:/home/sdci/docker/elasticsearch/data
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    container_name: elasticsearch3
    environment:
      - node.name=es03
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    privileged: true
    volumes:
      - esdata3:/home/sdci/docker/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.0
    container_name: kibana
    environment:
      SERVER_NAME: localhost
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    ports:
      - 5601:5601
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL

volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
  mndata1: 
    driver: local
  mndata2: 
    driver: local
  mndata3: 
    driver: local
  mndata4: 
    driver: local
